// Generated by scripts/sync-api-types.mjs from http://localhost:3000/api/docs-json.
// Do not edit by hand.

export type ConfirmSyncPairingDto = {
  decision:
    | 'seed'
    | 'restore'
    | 'reconcile'
    | 'merge'
    | 'replace-local'
    | 'replace-remote'
}
