// Generated by scripts/sync-api-types.mjs from http://127.0.0.1:3000/api/docs-json.
// Do not edit by hand.

export type CreateColumnDto = {
  "name": string;
  "title": string;
  "type": "text" | "date" | "number" | "image" | "link";
  "sortOrder"?: number;
  "isHidden"?: boolean;
  "config"?: Record<string, unknown> | null;
};
