// Generated by scripts/sync-api-types.mjs from http://127.0.0.1:3000/api/docs-json.
// Do not edit by hand.

import type { LabelsColumnConfigDto } from './labels-column-config.dto'

export type CreateColumnDto = {
  name: string
  title: string
  type: 'text' | 'date' | 'number' | 'image' | 'link' | 'labels'
  sortOrder?: number
  isHidden?: boolean
  config?: LabelsColumnConfigDto | Record<string, unknown> | null
}
