// Generated by scripts/sync-api-types.mjs from http://localhost:3000/api/docs-json.
// Do not edit by hand.

export type DeleteColumnQueryDto = {
  "deleteMode"?: "definitionOnly" | "definitionAndValues";
};
