// Generated by scripts/sync-api-types.mjs from http://127.0.0.1:3000/api/docs-json.
// Do not edit by hand.

import type { CreateTargetNoteTypeDto } from './create-target-note-type.dto'
import type { NoteTypeFieldMappingDto } from './note-type-field-mapping.dto'

export type DeleteNoteTypeDto = {
  mode: 'delete-notes' | 'move-notes'
  targetNoteTypeId?: string
  createTargetNoteType?: CreateTargetNoteTypeDto
  fieldMappings?: Array<NoteTypeFieldMappingDto>
}
