// Generated by scripts/sync-api-types.mjs from http://127.0.0.1:3000/api/docs-json.
// Do not edit by hand.

import type { ColumnDto } from './column.dto'
import type { GeneralSettingsDto } from './general-settings.dto'
import type { LabelDto } from './label.dto'
import type { NoteDto } from './note.dto'
import type { NoteTypeDto } from './note-type.dto'

export type ExportImportDataDto = {
  version: number
  exportedAt: string
  noteTypes: Array<NoteTypeDto>
  columns: Array<ColumnDto>
  labels: Array<LabelDto>
  generalSettings: GeneralSettingsDto
  notes: Array<NoteDto>
}
