// Generated by scripts/sync-api-types.mjs from http://localhost:3000/api/docs-json.
// Do not edit by hand.

import type { ColumnDto } from './column.dto';
import type { GeneralSettingsDto } from './general-settings.dto';
import type { NoteDto } from './note.dto';

export type ExportImportDataDto = {
  "version": number;
  "exportedAt": string;
  "columns": Array<ColumnDto>;
  "generalSettings": GeneralSettingsDto;
  "notes": Array<NoteDto>;
};
