// Generated by scripts/sync-api-types.mjs from http://127.0.0.1:3000/api/docs-json.
// Do not edit by hand.

export type ImportLabelIssueDto = {
  labelId?: string | null
  name?: string | null
  code:
    | 'duplicate-id'
    | 'duplicate-source-name'
    | 'invalid-definition'
    | 'invalid-reference'
    | 'unknown-source'
}
