// Generated by scripts/sync-api-types.mjs from http://127.0.0.1:3000/api/docs-json.
// Do not edit by hand.

export type ImportUnmatchedFieldDto = {
  name: string
  title?: string | null
  noteTypeTitle?: string | null
  type?: 'text' | 'date' | 'number' | 'image' | 'link' | null
}
