// Generated by scripts/sync-api-types.mjs from http://127.0.0.1:3000/api/docs-json.
// Do not edit by hand.

import type { ColumnDto } from './column.dto';

export type NoteTypeDetailDto = {
  "id": string;
  "title": string;
  "createdAt": string;
  "updatedAt": string;
  "columns": Array<ColumnDto>;
};
