// Generated by scripts/sync-api-types.mjs from http://127.0.0.1:3000/api/docs-json.
// Do not edit by hand.

export type NoteDto = {
  id: string
  noteTypeId: string
  values: Record<
    string,
    | string
    | number
    | {
        fileName?: string
        mimeType?: string
        size?: number
        dataUrl?: string
        path?: string
        url?: string
        altText?: string
        width?: number
        height?: number
        [key: string]: unknown
      }
    | Array<{
        fileName?: string
        mimeType?: string
        size?: number
        dataUrl?: string
        path?: string
        url?: string
        altText?: string
        width?: number
        height?: number
        [key: string]: unknown
      }>
  >
  createdAt: string
  updatedAt: string
}
