// Generated by scripts/sync-api-types.mjs from http://127.0.0.1:3000/api/docs-json.
// Do not edit by hand.

import type { BackgroundEnumDto } from './background-enum.dto'

export type NoteDto = {
  id: string
  noteTypeId: string
  background: BackgroundEnumDto | null
  values: Record<
    string,
    | string
    | number
    | Array<string>
    | {
        assetId?: string
        fileName?: string
        mimeType?: string
        size?: number
        dataUrl?: string
        path?: string
        url?: string
        altText?: string
        width?: number
        height?: number
        [key: string]: unknown
      }
    | Array<{
        assetId?: string
        fileName?: string
        mimeType?: string
        size?: number
        dataUrl?: string
        path?: string
        url?: string
        altText?: string
        width?: number
        height?: number
        [key: string]: unknown
      }>
  >
  createdAt: string
  updatedAt: string
}
