// Generated by scripts/sync-api-types.mjs from http://localhost:3000/api/docs-json.
// Do not edit by hand.

export type SyncStatusDto = {
  state:
    | 'disabled'
    | 'connecting'
    | 'syncing'
    | 'synced'
    | 'offline'
    | 'attention-required'
    | 'error'
  isEnabled: boolean
  provider?: 'google-drive' | 'one-drive' | null
  accountId?: string | null
  accountDisplayName?: string | null
  workspaceId?: string | null
  workspaceDisplayName?: string | null
  pendingMutationCount: number
  unresolvedConflictCount: number
  lastAttemptedAt?: string | null
  lastSucceededAt?: string | null
  lastErrorClassification?:
    | 'authentication-required'
    | 'offline'
    | 'throttled'
    | 'quota-exceeded'
    | 'provider-unavailable'
    | 'remote-attention-required'
    | 'unsupported-remote-version'
    | 'permanent'
    | 'unknown'
    | null
  lastTrigger?:
    | 'startup'
    | 'local-mutation'
    | 'manual'
    | 'focus'
    | 'resume'
    | 'network-recovery'
    | 'provider-signal'
    | 'watchdog'
    | 'post-push-verification'
    | 'quit'
    | 'conflict-resolution'
    | 'repair'
    | null
  isStartupReady: boolean
  dataRevision: number
}
