// Generated by scripts/sync-api-types.mjs from http://localhost:3000/api/docs-json.
// Do not edit by hand.

export type SyncTriggerDto = {
  trigger:
    | 'startup'
    | 'local-mutation'
    | 'manual'
    | 'focus'
    | 'background'
    | 'resume'
    | 'network-recovery'
    | 'provider-signal'
    | 'watchdog'
    | 'post-push-verification'
    | 'quit'
    | 'conflict-resolution'
    | 'repair'
}
