// Generated by scripts/sync-api-types.mjs from http://localhost:3000/api/docs-json.
// Do not edit by hand.

export type SyncConflictDto = {
  id: string
  workspaceId: string
  entityKind: 'workspace' | 'configuration' | 'note' | 'asset'
  entityId?: string | null
  conflictType:
    | 'edit-edit'
    | 'edit-delete'
    | 'uuid-collision'
    | 'invalid-reference'
    | 'remote-corruption'
  fieldPaths: Array<string>
  baseHash?: string | null
  localHash?: string | null
  remoteHash?: string | null
  baseDocumentJson?: string | null
  localDocumentJson?: string | null
  remoteDocumentJson?: string | null
  resolutionState:
    'unresolved' | 'resolved-local' | 'resolved-remote' | 'resolved-merged'
  conflictCopyEntityId?: string | null
  createdAt: string
  resolvedAt?: string | null
}
