// Generated by scripts/sync-api-types.mjs from http://localhost:3000/api/docs-json.
// Do not edit by hand.

export type SyncPairingOperationDto = {
  id: string
  operationType: 'pair' | 'switch'
  targetProvider: 'google-drive' | 'one-drive'
  accountId: string
  accountDisplayName?: string | null
  localWorkspaceId: string
  remoteWorkspaceId?: string | null
  remoteWorkspaceDisplayName?: string | null
  mode: 'seed' | 'restore' | 'reconcile' | 'mismatch'
  status: 'prepared' | 'applying' | 'completed' | 'cancelled' | 'failed'
  localIsPopulated: boolean
  remoteIsPopulated: boolean
  pendingMutationCount: number
  retainPendingWork: boolean
  previousProvider?: 'google-drive' | 'one-drive' | null
  previousAccountId?: string | null
  backupPath?: string | null
  decision?:
    | 'seed'
    | 'restore'
    | 'reconcile'
    | 'merge'
    | 'replace-local'
    | 'replace-remote'
    | null
  errorCode?: string | null
  createdAt: string
  updatedAt: string
  completedAt?: string | null
}
