// Generated by scripts/sync-api-types.mjs from http://localhost:3000/api/docs-json.
// Do not edit by hand.

export type UpdateColumnDto = {
  "name"?: string;
  "title"?: string;
  "type"?: "text" | "date" | "number" | "image" | "link";
  "sortOrder"?: number;
  "isHidden"?: boolean;
  "config"?: Record<string, unknown> | null;
};
