// Generated by scripts/sync-api-types.mjs from http://127.0.0.1:3000/api/docs-json.
// Do not edit by hand.

export type UpdateNoteBackgroundDto = {
  background:
    | 'CREAM'
    | 'LEMON'
    | 'LIME'
    | 'PEACH'
    | 'MAUVE'
    | 'SKY'
    | 'FLESH'
    | 'VERDE'
    | 'ROUGE'
    | 'TEAL'
    | 'OCHRE'
    | 'WHITE'
    | 'SILVER'
    | null
}
