// Generated by scripts/sync-api-types.mjs from http://localhost:3000/api/docs-json.
// Do not edit by hand.

export type UpdateNoteDto = {
  "values"?: Record<string, string | number | null | {
  "fileName"?: string;
  "mimeType"?: string;
  "size"?: number;
  "dataUrl"?: string;
  "path"?: string;
  "url"?: string;
  "altText"?: string;
  "width"?: number;
  "height"?: number;
  [key: string]: unknown;
}>;
};
