type OAuthInvalidRequestDetail =
  | 'malformed-client-id'
  | 'malformed-client-secret'
  | 'malformed-code'
  | 'malformed-code-verifier'
  | 'malformed-grant-type'
  | 'malformed-redirect-uri'
  | 'malformed-refresh-token'
  | 'malformed-scope'
  | 'missing-client-id'
  | 'missing-client-secret'
  | 'missing-code'
  | 'missing-code-verifier'
  | 'missing-grant-type'
  | 'missing-redirect-uri'
  | 'missing-refresh-token'
  | 'missing-scope'

type OAuthInvalidRequestDiagnosticCode =
  `oauth-${'authorization-code' | 'refresh-token'}-exchange-invalid-request-${OAuthInvalidRequestDetail}`
export type OAuthDiagnosticCode =
  | OAuthInvalidRequestDiagnosticCode
  | 'oauth-authorization-code-exchange-access-denied'
  | 'oauth-authorization-code-exchange-invalid-client'
  | 'oauth-authorization-code-exchange-invalid-grant'
  | 'oauth-authorization-code-exchange-invalid-request'
  | 'oauth-authorization-code-exchange-invalid-scope'
  | 'oauth-authorization-code-exchange-network-error'
  | 'oauth-authorization-code-exchange-provider-rejected'
  | 'oauth-authorization-code-exchange-unauthorized-client'
  | 'oauth-authorization-code-exchange-unsupported-grant-type'
  | 'oauth-authorization-code-response-invalid-json'
  | 'oauth-authorization-code-response-invalid-shape'
  | 'oauth-authorization-code-response-refresh-token-missing'
  | 'oauth-refresh-token-exchange-access-denied'
  | 'oauth-refresh-token-exchange-invalid-client'
  | 'oauth-refresh-token-exchange-invalid-grant'
  | 'oauth-refresh-token-exchange-invalid-request'
  | 'oauth-refresh-token-exchange-invalid-scope'
  | 'oauth-refresh-token-exchange-network-error'
  | 'oauth-refresh-token-exchange-provider-rejected'
  | 'oauth-refresh-token-exchange-unauthorized-client'
  | 'oauth-refresh-token-exchange-unsupported-grant-type'
  | 'oauth-refresh-token-response-invalid-json'
  | 'oauth-refresh-token-response-invalid-shape'
