export type OAuthInvalidRequestDetail =
  | 'malformed-client-id'
  | 'malformed-client-secret'
  | 'malformed-code'
  | 'malformed-code-verifier'
  | 'malformed-grant-type'
  | 'malformed-redirect-uri'
  | 'malformed-refresh-token'
  | 'malformed-scope'
  | 'missing-client-id'
  | 'missing-client-secret'
  | 'missing-code'
  | 'missing-code-verifier'
  | 'missing-grant-type'
  | 'missing-redirect-uri'
  | 'missing-refresh-token'
  | 'missing-scope'
